-- AlterTable
ALTER TABLE `contact` ADD COLUMN `inProgressAt` DATETIME(3) NULL,
    ADD COLUMN `resolutionNotes` TEXT NULL,
    ADD COLUMN `status` ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED_EMAIL', 'RESOLVED_PHONE', 'CLOSED') NOT NULL DEFAULT 'PENDING';
